import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import './globals.css';
import styles from './page.module.css';

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Practice Next.js web app',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  );
}
